set(MAHARAJAH_ENGINE_ROOT "${CMAKE_CURRENT_LIST_DIR}")

file(GLOB_RECURSE MAHARAJAH_ENGINE_SOURCES CONFIGURE_DEPENDS
  "${MAHARAJAH_ENGINE_ROOT}/src/*.c"
)

file(GLOB_RECURSE MAHARAJAH_ENGINE_HEADERS CONFIGURE_DEPENDS
  "${MAHARAJAH_ENGINE_ROOT}/include/*.h"
)

set(MAHARAJAH_ENGINE_INCLUDE_DIR "${MAHARAJAH_ENGINE_ROOT}/include")
